services:
  docs:
    image: leohakim_dev_local_docs
    container_name: leohakim_dev_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./leohakim_dev:/app/leohakim_dev:z
    ports:
      - '9000:9000'
    command: /start-docs
