#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${DATABASE_URL:-}" ]; then
    export DATABASE_URL="sqlite:////app/leohakim_dev.db"
fi

>&2 echo 'Starting application'

exec "$@"
